// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Kolyteon.Tests.Acceptance.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProblemRepresentationFeature : object, Xunit.IClassFixture<ProblemRepresentationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ProblemRepresentation.feature"
#line hidden
        
        public ProblemRepresentationFeature(ProblemRepresentationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Problem Representation", "Represent any valid instance of a given problem type as an immutable, serializabl" +
                    "e data structure.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Represent a Futoshiki problem")]
        [Xunit.TraitAttribute("FeatureTitle", "Problem Representation")]
        [Xunit.TraitAttribute("Description", "Represent a Futoshiki problem")]
        [Xunit.TraitAttribute("Category", "A/1")]
        public async System.Threading.Tasks.Task RepresentAFutoshikiProblem()
        {
            string[] tagsOfScenario = new string[] {
                    "A/1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Represent a Futoshiki problem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await testRunner.GivenAsync("I have created a Futoshiki problem matching the following diagram", "+---+---+---+---+\r\n|   | 2 <   |   |\r\n+-<-+---+---+->-+\r\n|   <   |   | 1 |\r\n+---+" +
                        "---+---+---+\r\n| 3 |   > 1 |   |\r\n+---+->-+---+---+\r\n| 4 >   |   | 3 |\r\n+---+---+" +
                        "---+---+", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
        await testRunner.AndAsync("I have serialized the Futoshiki problem to JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
        await testRunner.WhenAsync("I deserialize a Futoshiki problem from the JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
        await testRunner.ThenAsync("the deserialized and original Futoshiki problems should be equal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Represent a Graph Colouring problem")]
        [Xunit.TraitAttribute("FeatureTitle", "Problem Representation")]
        [Xunit.TraitAttribute("Description", "Represent a Graph Colouring problem")]
        [Xunit.TraitAttribute("Category", "B/1")]
        public async System.Threading.Tasks.Task RepresentAGraphColouringProblem()
        {
            string[] tagsOfScenario = new string[] {
                    "B/1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Represent a Graph Colouring problem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Node",
                            "Permitted Colours",
                            "Adjacent Nodes"});
                table3.AddRow(new string[] {
                            "A",
                            "Red, Blue, Green",
                            "B, C, D, G"});
                table3.AddRow(new string[] {
                            "B",
                            "Blue, Green",
                            "A, F"});
                table3.AddRow(new string[] {
                            "C",
                            "Red, Blue",
                            "A, G"});
                table3.AddRow(new string[] {
                            "D",
                            "Red, Blue",
                            "A, E, G, H"});
                table3.AddRow(new string[] {
                            "E",
                            "Blue, Green",
                            "D, F, G"});
                table3.AddRow(new string[] {
                            "F",
                            "Red, Green, Yellow",
                            "B, E"});
                table3.AddRow(new string[] {
                            "G",
                            "Red, Blue",
                            "A, C, D, E"});
                table3.AddRow(new string[] {
                            "H",
                            "Yellow",
                            "D"});
#line 25
        await testRunner.GivenAsync("I have created a Graph Colouring problem with the following nodes and edges", ((string)(null)), table3, "Given ");
#line hidden
#line 35
        await testRunner.AndAsync("I have serialized the Graph Colouring problem to JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
        await testRunner.WhenAsync("I deserialize a Graph Colouring problem from the JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
        await testRunner.ThenAsync("the deserialized and original Graph Colouring problems should be equal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Represent a Map Colouring problem")]
        [Xunit.TraitAttribute("FeatureTitle", "Problem Representation")]
        [Xunit.TraitAttribute("Description", "Represent a Map Colouring problem")]
        [Xunit.TraitAttribute("Category", "C/1")]
        public async System.Threading.Tasks.Task RepresentAMapColouringProblem()
        {
            string[] tagsOfScenario = new string[] {
                    "C/1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Represent a Map Colouring problem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Block",
                            "Permitted Colours"});
                table4.AddRow(new string[] {
                            "(0,6) [5x2]",
                            "Red, Blue, Green"});
                table4.AddRow(new string[] {
                            "(0,8) [10x2]",
                            "Red"});
                table4.AddRow(new string[] {
                            "(1,0) [3x1]",
                            "Red, Blue, Green"});
                table4.AddRow(new string[] {
                            "(1,1) [3x3]",
                            "Red, Yellow"});
                table4.AddRow(new string[] {
                            "(4,0) [4x2]",
                            "Red, Blue, Green"});
                table4.AddRow(new string[] {
                            "(4,4) [6x2]",
                            "Red, Blue, Green, Yellow"});
                table4.AddRow(new string[] {
                            "(5,6) [5x2]",
                            "Red, Blue, Green"});
                table4.AddRow(new string[] {
                            "(8,0) [2x1]",
                            "Red, Green"});
                table4.AddRow(new string[] {
                            "(8,1) [2x1]",
                            "Blue"});
#line 41
        await testRunner.GivenAsync("I have created a Map Colouring problem with a 10x10 canvas and the following bloc" +
                        "ks", ((string)(null)), table4, "Given ");
#line hidden
#line 52
        await testRunner.AndAsync("I have serialized the Map Colouring problem to JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
        await testRunner.WhenAsync("I deserialize a Map Colouring problem from the JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
        await testRunner.ThenAsync("the deserialized and original Map Colouring problems should be equal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Represent an N-Queens problem")]
        [Xunit.TraitAttribute("FeatureTitle", "Problem Representation")]
        [Xunit.TraitAttribute("Description", "Represent an N-Queens problem")]
        [Xunit.TraitAttribute("Category", "D/1")]
        public async System.Threading.Tasks.Task RepresentAnN_QueensProblem()
        {
            string[] tagsOfScenario = new string[] {
                    "D/1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Represent an N-Queens problem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
        await testRunner.GivenAsync("I have created an N-Queens problem for N = 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
        await testRunner.AndAsync("I have serialized the N-Queens problem to JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
        await testRunner.WhenAsync("I deserialize an N-Queens problem from the JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
        await testRunner.ThenAsync("the deserialized and original N-Queens problems should be equal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Represent a Shikaku problem")]
        [Xunit.TraitAttribute("FeatureTitle", "Problem Representation")]
        [Xunit.TraitAttribute("Description", "Represent a Shikaku problem")]
        [Xunit.TraitAttribute("Category", "E/1")]
        public async System.Threading.Tasks.Task RepresentAShikakuProblem()
        {
            string[] tagsOfScenario = new string[] {
                    "E/1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Represent a Shikaku problem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
        await testRunner.GivenAsync("I have created a Shikaku problem from the following grid", @"03 __ __ __ __ __ __ 07 __ __
__ __ __ __ __ __ __ __ __ __
__ __ __ __ __ __ __ __ __ __
__ __ __ 14 __ __ __ __ __ __
__ __ __ __ __ __ __ __ __ __
05 __ 10 __ __ __ 21 __ __ __
03 __ __ __ __ __ __ __ __ __
__ __ 03 __ __ __ __ __ __ __
__ __ __ __ __ __ __ 16 __ __
__ __ __ __ __ __ __ __ __ 18", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
        await testRunner.AndAsync("I have serialized the Shikaku problem to JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
        await testRunner.WhenAsync("I deserialize a Shikaku problem from the JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 80
        await testRunner.ThenAsync("the deserialized and original Shikaku problems should be equal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Represent a Sudoku problem")]
        [Xunit.TraitAttribute("FeatureTitle", "Problem Representation")]
        [Xunit.TraitAttribute("Description", "Represent a Sudoku problem")]
        [Xunit.TraitAttribute("Category", "F/1")]
        public async System.Threading.Tasks.Task RepresentASudokuProblem()
        {
            string[] tagsOfScenario = new string[] {
                    "F/1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Represent a Sudoku problem", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 84
        await testRunner.GivenAsync("I have created a Sudoku problem from the following grid", "02 __ 04 05 06 __ 09 01 03\r\n01 05 09 03 04 02 06 __ 07\r\n08 03 __ __ __ __ 02 05 0" +
                        "4\r\n03 02 01 06 __ __ __ __ 09\r\n09 __ 05 __ __ __ 01 __ 02\r\n06 04 07 02 01 09 05 " +
                        "__ 08\r\n__ __ 08 09 __ 06 03 04 05\r\n__ 06 02 04 07 __ __ 09 01\r\n04 __ 03 08 __ 01" +
                        " 07 02 06", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
        await testRunner.AndAsync("I have serialized the Sudoku problem to JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
        await testRunner.WhenAsync("I deserialize a Sudoku problem from the JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
        await testRunner.ThenAsync("the deserialized and original Sudoku problems should be equal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ProblemRepresentationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ProblemRepresentationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
