// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Kolyteon.Tests.Acceptance.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SolutionVerificationFeature : object, Xunit.IClassFixture<SolutionVerificationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SolutionVerification.feature"
#line hidden
        
        public SolutionVerificationFeature(SolutionVerificationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Solution Verification", "Verify the correctness of any proposed solution to any valid instance of a given " +
                    "problem type.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Graph Colouring problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Graph Colouring problem solution")]
        [Xunit.TraitAttribute("Category", "B/2")]
        public async System.Threading.Tasks.Task VerifyAGraphColouringProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "B/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Graph Colouring problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Node",
                            "Permitted Colours",
                            "Adjacent Nodes"});
                table3.AddRow(new string[] {
                            "x1",
                            "Red, Blue, Green",
                            "x2, x3, x4, x7"});
                table3.AddRow(new string[] {
                            "x2",
                            "Blue, Green",
                            "x1, x6"});
                table3.AddRow(new string[] {
                            "x3",
                            "Red, Blue",
                            "x1, x7"});
                table3.AddRow(new string[] {
                            "x4",
                            "Red, Blue",
                            "x1, x5, x7"});
                table3.AddRow(new string[] {
                            "x5",
                            "Blue, Green",
                            "x4, x6, x7"});
                table3.AddRow(new string[] {
                            "x6",
                            "Red, Green, Yellow",
                            "x2, x5"});
                table3.AddRow(new string[] {
                            "x7",
                            "Red, Blue",
                            "x1, x3, x4, x5"});
#line 7
        await testRunner.GivenAsync("I have created a Graph Colouring problem with the following nodes and edges", ((string)(null)), table3, "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Node",
                            "Colour"});
                table4.AddRow(new string[] {
                            "x1",
                            "Green"});
                table4.AddRow(new string[] {
                            "x2",
                            "Blue"});
                table4.AddRow(new string[] {
                            "x3",
                            "Red"});
                table4.AddRow(new string[] {
                            "x4",
                            "Red"});
                table4.AddRow(new string[] {
                            "x5",
                            "Green"});
                table4.AddRow(new string[] {
                            "x6",
                            "Yellow"});
                table4.AddRow(new string[] {
                            "x7",
                            "Blue"});
#line 16
        await testRunner.AndAsync("I have proposed the following node and colour dictionary as a solution to the Gra" +
                        "ph Colouring problem", ((string)(null)), table4, "And ");
#line hidden
#line 25
        await testRunner.WhenAsync("I ask the Graph Colouring problem to verify the correctness of the proposed solut" +
                        "ion", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Map Colouring problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Map Colouring problem solution")]
        [Xunit.TraitAttribute("Category", "C/2")]
        public async System.Threading.Tasks.Task VerifyAMapColouringProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "C/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Map Colouring problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Block",
                            "Permitted Colours"});
                table5.AddRow(new string[] {
                            "(0,6) [5x2]",
                            "Red, Blue, Green"});
                table5.AddRow(new string[] {
                            "(0,8) [10x2]",
                            "Red"});
                table5.AddRow(new string[] {
                            "(1,0) [3x1]",
                            "Red, Blue, Green"});
                table5.AddRow(new string[] {
                            "(1,1) [3x3]",
                            "Red, Yellow"});
                table5.AddRow(new string[] {
                            "(4,0) [4x2]",
                            "Red, Blue, Green"});
                table5.AddRow(new string[] {
                            "(4,4) [6x2]",
                            "Red, Blue, Green, Yellow"});
                table5.AddRow(new string[] {
                            "(5,6) [5x2]",
                            "Red, Blue, Green"});
                table5.AddRow(new string[] {
                            "(8,0) [2x1]",
                            "Red, Green"});
                table5.AddRow(new string[] {
                            "(8,1) [1x1]",
                            "Red"});
                table5.AddRow(new string[] {
                            "(9,1) [1x1]",
                            "Yellow"});
#line 30
        await testRunner.GivenAsync("I have created a Map Colouring problem with a 10x10 canvas and the following bloc" +
                        "ks", ((string)(null)), table5, "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Block",
                            "Colour"});
                table6.AddRow(new string[] {
                            "(0,6) [5x2]",
                            "Blue"});
                table6.AddRow(new string[] {
                            "(0,8) [10x2]",
                            "Red"});
                table6.AddRow(new string[] {
                            "(1,0) [3x1]",
                            "Red"});
                table6.AddRow(new string[] {
                            "(1,1) [3x3]",
                            "Yellow"});
                table6.AddRow(new string[] {
                            "(4,0) [4x2]",
                            "Blue"});
                table6.AddRow(new string[] {
                            "(4,4) [6x2]",
                            "Red"});
                table6.AddRow(new string[] {
                            "(5,6) [5x2]",
                            "Green"});
                table6.AddRow(new string[] {
                            "(8,0) [2x1]",
                            "Green"});
                table6.AddRow(new string[] {
                            "(8,1) [1x1]",
                            "Red"});
                table6.AddRow(new string[] {
                            "(9,1) [1x1]",
                            "Yellow"});
#line 42
        await testRunner.AndAsync("I have proposed the following block and colour dictionary as a solution to the Ma" +
                        "p Colouring problem", ((string)(null)), table6, "And ");
#line hidden
#line 54
        await testRunner.WhenAsync("I ask the Map Colouring problem to verify the correctness of the proposed solutio" +
                        "n", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify an N-Queens problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify an N-Queens problem solution")]
        [Xunit.TraitAttribute("Category", "D/2")]
        public async System.Threading.Tasks.Task VerifyAnN_QueensProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "D/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify an N-Queens problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
        await testRunner.GivenAsync("I have created an N-Queens problem for N = 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Square"});
                table7.AddRow(new string[] {
                            "(0,6)"});
                table7.AddRow(new string[] {
                            "(1,4)"});
                table7.AddRow(new string[] {
                            "(2,2)"});
                table7.AddRow(new string[] {
                            "(3,0)"});
                table7.AddRow(new string[] {
                            "(4,5)"});
                table7.AddRow(new string[] {
                            "(5,7)"});
                table7.AddRow(new string[] {
                            "(6,1)"});
                table7.AddRow(new string[] {
                            "(7,3)"});
#line 60
        await testRunner.AndAsync("I have proposed the following squares as a solution to the N-Queens problem", ((string)(null)), table7, "And ");
#line hidden
#line 70
        await testRunner.WhenAsync("I ask the N-Queens problem to verify the correctness of the proposed solution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Shikaku problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Shikaku problem solution")]
        [Xunit.TraitAttribute("Category", "E/2")]
        public async System.Threading.Tasks.Task VerifyAShikakuProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "E/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Shikaku problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 74
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
        await testRunner.GivenAsync("I have created a Shikaku problem from the following grid", @"03 __ __ __ __ __ __ 07 __ __
__ __ __ __ __ __ __ __ __ __
__ __ __ __ __ __ __ __ __ __
__ __ __ 14 __ __ __ __ __ __
__ __ __ __ __ __ __ __ __ __
05 __ 10 __ __ __ 21 __ __ __
03 __ __ __ __ __ __ __ __ __
__ __ 03 __ __ __ __ __ __ __
__ __ __ __ __ __ __ 16 __ __
__ __ __ __ __ __ __ __ __ 18", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Block"});
                table8.AddRow(new string[] {
                            "(0,0) [3x1]"});
                table8.AddRow(new string[] {
                            "(0,1) [1x5]"});
                table8.AddRow(new string[] {
                            "(0,6) [3x1]"});
                table8.AddRow(new string[] {
                            "(0,7) [3x1]"});
                table8.AddRow(new string[] {
                            "(0,8) [8x2]"});
                table8.AddRow(new string[] {
                            "(1,1) [2x5]"});
                table8.AddRow(new string[] {
                            "(3,0) [7x1]"});
                table8.AddRow(new string[] {
                            "(3,1) [2x7]"});
                table8.AddRow(new string[] {
                            "(5,1) [3x7]"});
                table8.AddRow(new string[] {
                            "(8,1) [2x9]"});
#line 88
        await testRunner.AndAsync("I have proposed the following blocks as a solution to the Shikaku problem", ((string)(null)), table8, "And ");
#line hidden
#line 100
        await testRunner.WhenAsync("I ask the Shikaku problem to verify the correctness of the proposed solution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 101
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Sudoku problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Sudoku problem solution")]
        [Xunit.TraitAttribute("Category", "F/2")]
        public async System.Threading.Tasks.Task VerifyASudokuProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "F/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Sudoku problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 104
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 105
        await testRunner.GivenAsync("I have created a Sudoku problem from the following grid", "02 __ 04 05 06 __ 09 01 03\r\n01 05 09 03 04 02 06 __ 07\r\n08 03 __ __ __ __ 02 05 0" +
                        "4\r\n03 02 01 06 __ __ __ __ 09\r\n09 __ 05 __ __ __ 01 __ 02\r\n06 04 07 02 01 09 05 " +
                        "__ 08\r\n__ __ 08 09 __ 06 03 04 05\r\n__ 06 02 04 07 __ __ 09 01\r\n04 __ 03 08 __ 01" +
                        " 07 02 06", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Filled Square"});
                table9.AddRow(new string[] {
                            "(0,6) [7]"});
                table9.AddRow(new string[] {
                            "(0,7) [5]"});
                table9.AddRow(new string[] {
                            "(1,0) [7]"});
                table9.AddRow(new string[] {
                            "(1,4) [8]"});
                table9.AddRow(new string[] {
                            "(1,6) [1]"});
                table9.AddRow(new string[] {
                            "(1,8) [9]"});
                table9.AddRow(new string[] {
                            "(2,2) [6]"});
                table9.AddRow(new string[] {
                            "(3,2) [1]"});
                table9.AddRow(new string[] {
                            "(3,4) [7]"});
                table9.AddRow(new string[] {
                            "(4,2) [9]"});
                table9.AddRow(new string[] {
                            "(4,3) [8]"});
                table9.AddRow(new string[] {
                            "(4,4) [3]"});
                table9.AddRow(new string[] {
                            "(4,6) [2]"});
                table9.AddRow(new string[] {
                            "(4,8) [5]"});
                table9.AddRow(new string[] {
                            "(5,0) [8]"});
                table9.AddRow(new string[] {
                            "(5,2) [7]"});
                table9.AddRow(new string[] {
                            "(5,3) [5]"});
                table9.AddRow(new string[] {
                            "(5,4) [4]"});
                table9.AddRow(new string[] {
                            "(5,7) [3]"});
                table9.AddRow(new string[] {
                            "(6,3) [4]"});
                table9.AddRow(new string[] {
                            "(6,7) [8]"});
                table9.AddRow(new string[] {
                            "(7,1) [8]"});
                table9.AddRow(new string[] {
                            "(7,3) [7]"});
                table9.AddRow(new string[] {
                            "(7,4) [6]"});
                table9.AddRow(new string[] {
                            "(7,5) [3]"});
#line 117
        await testRunner.AndAsync("I have proposed the following filled squares as a solution to the Sudoku problem", ((string)(null)), table9, "And ");
#line hidden
#line 144
        await testRunner.WhenAsync("I ask the Sudoku problem to verify the correctness of the proposed solution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 145
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SolutionVerificationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SolutionVerificationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
