// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Kolyteon.Tests.Acceptance.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SolutionVerificationFeature : object, Xunit.IClassFixture<SolutionVerificationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SolutionVerification.feature"
#line hidden
        
        public SolutionVerificationFeature(SolutionVerificationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Solution Verification", "Verify the correctness of any proposed solution to any valid instance of a given " +
                    "problem type.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Futoshiki problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Futoshiki problem solution")]
        [Xunit.TraitAttribute("Category", "A/2")]
        public async System.Threading.Tasks.Task VerifyAFutoshikiProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "A/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Futoshiki problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await testRunner.GivenAsync("I have created a Futoshiki problem matching the following diagram", "+---+---+---+---+\r\n|   | 2 <   |   |\r\n+-<-+---+---+->-+\r\n|   <   |   | 1 |\r\n+---+" +
                        "---+---+---+\r\n| 3 |   > 1 |   |\r\n+---+->-+---+---+\r\n| 4 >   |   | 3 |\r\n+---+---+" +
                        "---+---+", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Filled Square"});
                table7.AddRow(new string[] {
                            "(0,0) [1]"});
                table7.AddRow(new string[] {
                            "(0,1) [2]"});
                table7.AddRow(new string[] {
                            "(1,1) [3]"});
                table7.AddRow(new string[] {
                            "(1,2) [4]"});
                table7.AddRow(new string[] {
                            "(1,3) [1]"});
                table7.AddRow(new string[] {
                            "(2,0) [3]"});
                table7.AddRow(new string[] {
                            "(2,1) [4]"});
                table7.AddRow(new string[] {
                            "(2,3) [2]"});
                table7.AddRow(new string[] {
                            "(3,0) [4]"});
                table7.AddRow(new string[] {
                            "(3,2) [2]"});
#line 19
        await testRunner.AndAsync("I have proposed the following filled squares as a solution to the Futoshiki probl" +
                        "em", ((string)(null)), table7, "And ");
#line hidden
#line 31
        await testRunner.WhenAsync("I ask the Futoshiki problem to verify the correctness of the proposed solution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Graph Colouring problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Graph Colouring problem solution")]
        [Xunit.TraitAttribute("Category", "B/2")]
        public async System.Threading.Tasks.Task VerifyAGraphColouringProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "B/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Graph Colouring problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Node",
                            "Permitted Colours",
                            "Adjacent Nodes"});
                table8.AddRow(new string[] {
                            "A",
                            "Red, Blue, Green",
                            "B, C, D, G"});
                table8.AddRow(new string[] {
                            "B",
                            "Blue, Green",
                            "A, F"});
                table8.AddRow(new string[] {
                            "C",
                            "Red, Blue",
                            "A, G"});
                table8.AddRow(new string[] {
                            "D",
                            "Red, Blue",
                            "A, E, G, H"});
                table8.AddRow(new string[] {
                            "E",
                            "Blue, Green",
                            "D, F, G"});
                table8.AddRow(new string[] {
                            "F",
                            "Red, Green, Yellow",
                            "B, E"});
                table8.AddRow(new string[] {
                            "G",
                            "Red, Blue",
                            "A, C, D, E"});
                table8.AddRow(new string[] {
                            "H",
                            "Yellow",
                            "D"});
#line 36
        await testRunner.GivenAsync("I have created a Graph Colouring problem with the following nodes and edges", ((string)(null)), table8, "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Node",
                            "Colour"});
                table9.AddRow(new string[] {
                            "A",
                            "Green"});
                table9.AddRow(new string[] {
                            "B",
                            "Blue"});
                table9.AddRow(new string[] {
                            "C",
                            "Red"});
                table9.AddRow(new string[] {
                            "D",
                            "Red"});
                table9.AddRow(new string[] {
                            "E",
                            "Green"});
                table9.AddRow(new string[] {
                            "F",
                            "Yellow"});
                table9.AddRow(new string[] {
                            "G",
                            "Blue"});
                table9.AddRow(new string[] {
                            "H",
                            "Yellow"});
#line 46
        await testRunner.AndAsync("I have proposed the following node and colour dictionary as a solution to the Gra" +
                        "ph Colouring problem", ((string)(null)), table9, "And ");
#line hidden
#line 56
        await testRunner.WhenAsync("I ask the Graph Colouring problem to verify the correctness of the proposed solut" +
                        "ion", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Map Colouring problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Map Colouring problem solution")]
        [Xunit.TraitAttribute("Category", "C/2")]
        public async System.Threading.Tasks.Task VerifyAMapColouringProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "C/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Map Colouring problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Block",
                            "Permitted Colours"});
                table10.AddRow(new string[] {
                            "(0,6) [5x2]",
                            "Red, Blue, Green"});
                table10.AddRow(new string[] {
                            "(0,8) [10x2]",
                            "Red"});
                table10.AddRow(new string[] {
                            "(1,0) [3x1]",
                            "Red, Blue, Green"});
                table10.AddRow(new string[] {
                            "(1,1) [3x3]",
                            "Red, Yellow"});
                table10.AddRow(new string[] {
                            "(4,0) [4x2]",
                            "Red, Blue, Green"});
                table10.AddRow(new string[] {
                            "(4,4) [6x2]",
                            "Red, Blue, Green, Yellow"});
                table10.AddRow(new string[] {
                            "(5,6) [5x2]",
                            "Red, Blue, Green"});
                table10.AddRow(new string[] {
                            "(8,0) [2x1]",
                            "Red, Green"});
                table10.AddRow(new string[] {
                            "(8,1) [2x1]",
                            "Blue"});
#line 61
        await testRunner.GivenAsync("I have created a Map Colouring problem with a 10x10 canvas and the following bloc" +
                        "ks", ((string)(null)), table10, "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Block",
                            "Colour"});
                table11.AddRow(new string[] {
                            "(0,6) [5x2]",
                            "Green"});
                table11.AddRow(new string[] {
                            "(0,8) [10x2]",
                            "Red"});
                table11.AddRow(new string[] {
                            "(1,0) [3x1]",
                            "Blue"});
                table11.AddRow(new string[] {
                            "(1,1) [3x3]",
                            "Red"});
                table11.AddRow(new string[] {
                            "(4,0) [4x2]",
                            "Green"});
                table11.AddRow(new string[] {
                            "(4,4) [6x2]",
                            "Yellow"});
                table11.AddRow(new string[] {
                            "(5,6) [5x2]",
                            "Blue"});
                table11.AddRow(new string[] {
                            "(8,0) [2x1]",
                            "Red"});
                table11.AddRow(new string[] {
                            "(8,1) [2x1]",
                            "Blue"});
#line 72
        await testRunner.AndAsync("I have proposed the following block and colour dictionary as a solution to the Ma" +
                        "p Colouring problem", ((string)(null)), table11, "And ");
#line hidden
#line 83
        await testRunner.WhenAsync("I ask the Map Colouring problem to verify the correctness of the proposed solutio" +
                        "n", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify an N-Queens problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify an N-Queens problem solution")]
        [Xunit.TraitAttribute("Category", "D/2")]
        public async System.Threading.Tasks.Task VerifyAnN_QueensProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "D/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify an N-Queens problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
        await testRunner.GivenAsync("I have created an N-Queens problem for N = 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Square"});
                table12.AddRow(new string[] {
                            "(0,4)"});
                table12.AddRow(new string[] {
                            "(1,1)"});
                table12.AddRow(new string[] {
                            "(2,3)"});
                table12.AddRow(new string[] {
                            "(3,0)"});
                table12.AddRow(new string[] {
                            "(4,2)"});
#line 89
        await testRunner.AndAsync("I have proposed the following squares as a solution to the N-Queens problem", ((string)(null)), table12, "And ");
#line hidden
#line 96
        await testRunner.WhenAsync("I ask the N-Queens problem to verify the correctness of the proposed solution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 97
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Shikaku problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Shikaku problem solution")]
        [Xunit.TraitAttribute("Category", "E/2")]
        public async System.Threading.Tasks.Task VerifyAShikakuProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "E/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Shikaku problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 100
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 101
        await testRunner.GivenAsync("I have created a Shikaku problem from the following grid", "05 __ __ __ __\r\n__ __ 08 __ __\r\n__ __ __ 04 __\r\n__ __ __ 06 02\r\n__ __ __ __ __", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Block"});
                table13.AddRow(new string[] {
                            "(0,0) [1x5]"});
                table13.AddRow(new string[] {
                            "(1,0) [4x2]"});
                table13.AddRow(new string[] {
                            "(1,2) [4x1]"});
                table13.AddRow(new string[] {
                            "(1,3) [3x2]"});
                table13.AddRow(new string[] {
                            "(4,3) [1x2]"});
#line 109
        await testRunner.AndAsync("I have proposed the following blocks as a solution to the Shikaku problem", ((string)(null)), table13, "And ");
#line hidden
#line 116
        await testRunner.WhenAsync("I ask the Shikaku problem to verify the correctness of the proposed solution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Verify a Sudoku problem solution")]
        [Xunit.TraitAttribute("FeatureTitle", "Solution Verification")]
        [Xunit.TraitAttribute("Description", "Verify a Sudoku problem solution")]
        [Xunit.TraitAttribute("Category", "F/2")]
        public async System.Threading.Tasks.Task VerifyASudokuProblemSolution()
        {
            string[] tagsOfScenario = new string[] {
                    "F/2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify a Sudoku problem solution", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 121
        await testRunner.GivenAsync("I have created a Sudoku problem from the following grid", "__ 02 __ __ __ 06 07 08 __\r\n__ 05 06 07 08 09 01 02 03\r\n__ 08 09 01 02 03 04 05 0" +
                        "6\r\n08 09 01 02 03 04 05 06 07\r\n02 03 04 05 __ 07 08 09 01\r\n05 06 07 08 09 01 02 " +
                        "03 04\r\n06 07 08 09 01 02 03 04 05\r\n09 01 02 03 04 05 06 07 08\r\n__ 04 05 06 __ 08" +
                        " 09 01 __", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Filled Square"});
                table14.AddRow(new string[] {
                            "(0,0) [1]"});
                table14.AddRow(new string[] {
                            "(0,1) [4]"});
                table14.AddRow(new string[] {
                            "(0,2) [7]"});
                table14.AddRow(new string[] {
                            "(0,8) [3]"});
                table14.AddRow(new string[] {
                            "(2,0) [3]"});
                table14.AddRow(new string[] {
                            "(3,0) [4]"});
                table14.AddRow(new string[] {
                            "(4,0) [5]"});
                table14.AddRow(new string[] {
                            "(4,4) [6]"});
                table14.AddRow(new string[] {
                            "(4,8) [7]"});
                table14.AddRow(new string[] {
                            "(8,0) [9]"});
                table14.AddRow(new string[] {
                            "(8,8) [2]"});
#line 133
        await testRunner.AndAsync("I have proposed the following filled squares as a solution to the Sudoku problem", ((string)(null)), table14, "And ");
#line hidden
#line 146
        await testRunner.WhenAsync("I ask the Sudoku problem to verify the correctness of the proposed solution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 147
        await testRunner.ThenAsync("the verification result should be successful", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SolutionVerificationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SolutionVerificationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
