// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mjt85.Kolyteon.FeatureTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class N_QueensFeature : object, Xunit.IClassFixture<N_QueensFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "NQueens.feature"
#line hidden
        
        public N_QueensFeature(N_QueensFeature.FixtureData fixtureData, Mjt85_Kolyteon_FeatureTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "N-Queens", "As a developer, I want to represent any N-Queens puzzle in code so that I can mod" +
                    "el and solve it as a binary CSP", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create a serializable puzzle")]
        [Xunit.TraitAttribute("FeatureTitle", "N-Queens")]
        [Xunit.TraitAttribute("Description", "Create a serializable puzzle")]
        public void CreateASerializablePuzzle()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a serializable puzzle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
        testRunner.Given("I have created an N-Queens puzzle in which N = 8", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
        testRunner.And("I have serialized the N-Queens puzzle to JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 7
        testRunner.When("I deserialize an N-Queens puzzle from the JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
        testRunner.Then("the deserialized N-Queens puzzle should be the same as the original puzzle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Confirm a proposed solution is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "N-Queens")]
        [Xunit.TraitAttribute("Description", "Confirm a proposed solution is valid")]
        public void ConfirmAProposedSolutionIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Confirm a proposed solution is valid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
        testRunner.Given("I have created an N-Queens puzzle in which N = 8", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Column",
                            "Row"});
                table10.AddRow(new string[] {
                            "0",
                            "6"});
                table10.AddRow(new string[] {
                            "1",
                            "4"});
                table10.AddRow(new string[] {
                            "2",
                            "2"});
                table10.AddRow(new string[] {
                            "3",
                            "0"});
                table10.AddRow(new string[] {
                            "4",
                            "5"});
                table10.AddRow(new string[] {
                            "5",
                            "7"});
                table10.AddRow(new string[] {
                            "6",
                            "1"});
                table10.AddRow(new string[] {
                            "7",
                            "3"});
#line 12
        testRunner.And("I have obtained the following list of queens as a proposed solution to the N-Quee" +
                        "ns puzzle", ((string)(null)), table10, "And ");
#line hidden
#line 22
        testRunner.When("I ask the N-Queens puzzle to validate the proposed solution", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
        testRunner.Then("the validation result should be successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Model a puzzle as a binary CSP")]
        [Xunit.TraitAttribute("FeatureTitle", "N-Queens")]
        [Xunit.TraitAttribute("Description", "Model a puzzle as a binary CSP")]
        public void ModelAPuzzleAsABinaryCSP()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Model a puzzle as a binary CSP", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
        testRunner.Given("I have created an N-Queens puzzle in which N = 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
        testRunner.And("I have modelled the N-Queens puzzle as a binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
        testRunner.When("I request the binary CSP metrics for the N-Queens puzzle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table11.AddRow(new string[] {
                            "Variables",
                            "5"});
                table11.AddRow(new string[] {
                            "Constraints",
                            "10"});
                table11.AddRow(new string[] {
                            "ConstraintDensity",
                            "1"});
                table11.AddRow(new string[] {
                            "ConstraintTightness",
                            "0.44"});
#line 29
        testRunner.Then("the binary CSP problem metrics should be as follows", ((string)(null)), table11, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table12.AddRow(new string[] {
                            "MinimumValue",
                            "5"});
                table12.AddRow(new string[] {
                            "MeanValue",
                            "5"});
                table12.AddRow(new string[] {
                            "MaximumValue",
                            "5"});
                table12.AddRow(new string[] {
                            "DistinctValues",
                            "1"});
#line 35
        testRunner.And("the binary CSP variable domain size statistics should be as follows", ((string)(null)), table12, "And ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table13.AddRow(new string[] {
                            "MinimumValue",
                            "4"});
                table13.AddRow(new string[] {
                            "MeanValue",
                            "4"});
                table13.AddRow(new string[] {
                            "MaximumValue",
                            "4"});
                table13.AddRow(new string[] {
                            "DistinctValues",
                            "1"});
#line 41
        testRunner.And("the binary CSP variable degree statistics should be as follows", ((string)(null)), table13, "And ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table14.AddRow(new string[] {
                            "MinimumValue",
                            "1.6"});
                table14.AddRow(new string[] {
                            "MeanValue",
                            "1.76"});
                table14.AddRow(new string[] {
                            "MaximumValue",
                            "1.92"});
                table14.AddRow(new string[] {
                            "DistinctValues",
                            "3"});
#line 47
        testRunner.And("the binary CSP variable sum tightness statistics should be as follows", ((string)(null)), table14, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Solve a binary CSP modelling a solvable puzzle")]
        [Xunit.TraitAttribute("FeatureTitle", "N-Queens")]
        [Xunit.TraitAttribute("Description", "Solve a binary CSP modelling a solvable puzzle")]
        [Xunit.InlineDataAttribute("Backtracking", "None", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "MaxCardinality", new string[0])]
        public void SolveABinaryCSPModellingASolvablePuzzle(string search, string ordering, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Search", search);
            argumentsOfScenario.Add("Ordering", ordering);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Solve a binary CSP modelling a solvable puzzle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 55
        testRunner.Given("I have created an N-Queens puzzle in which N = 8", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 56
        testRunner.And("I have modelled the N-Queens puzzle as a binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
        testRunner.And(string.Format("I have set the N-Queens binary CSP solver to use the \'{0}\' search strategy", search), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
        testRunner.And(string.Format("I have set the N-Queens binary CSP solver to use the \'{0}\' ordering strategy", ordering), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
        testRunner.When("I run the N-Queens binary CSP solver on the binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 60
        testRunner.And("I ask the N-Queens puzzle to validate the proposed solution", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 61
        testRunner.Then("the validation result should be successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                N_QueensFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                N_QueensFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
