// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mjt85.Kolyteon.FeatureTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ShikakuFeature : object, Xunit.IClassFixture<ShikakuFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Shikaku.feature"
#line hidden
        
        public ShikakuFeature(ShikakuFeature.FixtureData fixtureData, Mjt85_Kolyteon_FeatureTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Shikaku", "As a developer, I want to represent any Shikaku puzzle in code so that I can mode" +
                    "l and solve it as a binary CSP.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create a serializable puzzle")]
        [Xunit.TraitAttribute("FeatureTitle", "Shikaku")]
        [Xunit.TraitAttribute("Description", "Create a serializable puzzle")]
        public void CreateASerializablePuzzle()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a serializable puzzle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
        testRunner.Given("I have created a Shikaku puzzle from the following grid", "05 __ __ __ __\r\n__ 05 __ __ __\r\n__ __ 09 __ __\r\n__ __ __ __ 03\r\n03 __ __ __ __", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
        testRunner.And("I have serialized the Shikaku puzzle to JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
        testRunner.When("I deserialize a Shikaku puzzle from the JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
        testRunner.Then("the deserialized Shikaku puzzle should be the same as the original puzzle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Confirm a proposed solution is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "Shikaku")]
        [Xunit.TraitAttribute("Description", "Confirm a proposed solution is valid")]
        public void ConfirmAProposedSolutionIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Confirm a proposed solution is valid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
        testRunner.Given("I have created a Shikaku puzzle from the following grid", "05 __ __ __ __\r\n__ 05 __ __ __\r\n__ __ 09 __ __\r\n__ __ __ __ 03\r\n03 __ __ __ __", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "OriginColumn",
                            "OriginRow",
                            "WidthInCells",
                            "HeightInCells"});
                table15.AddRow(new string[] {
                            "0",
                            "0",
                            "5",
                            "1"});
                table15.AddRow(new string[] {
                            "0",
                            "1",
                            "5",
                            "1"});
                table15.AddRow(new string[] {
                            "0",
                            "2",
                            "1",
                            "3"});
                table15.AddRow(new string[] {
                            "1",
                            "2",
                            "3",
                            "3"});
                table15.AddRow(new string[] {
                            "4",
                            "2",
                            "1",
                            "3"});
#line 26
        testRunner.And("I have obtained the following list of rectangles as a proposed solution to the Sh" +
                        "ikaku puzzle", ((string)(null)), table15, "And ");
#line hidden
#line 33
        testRunner.When("I ask the Shikaku puzzle to validate the proposed solution", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
        testRunner.Then("the validation result should be successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Model a puzzle as a binary CSP")]
        [Xunit.TraitAttribute("FeatureTitle", "Shikaku")]
        [Xunit.TraitAttribute("Description", "Model a puzzle as a binary CSP")]
        public void ModelAPuzzleAsABinaryCSP()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Model a puzzle as a binary CSP", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 37
        testRunner.Given("I have created a Shikaku puzzle from the following grid", "__ __ 09 __ __\r\n__ __ __ __ 10\r\n__ __ __ __ __\r\n__ 04 02 __ __\r\n__ __ __ __ __", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 45
        testRunner.And("I have modelled the Shikaku puzzle as a binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
        testRunner.When("I request the binary CSP metrics for the Shikaku puzzle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table16.AddRow(new string[] {
                            "Variables",
                            "4"});
                table16.AddRow(new string[] {
                            "Constraints",
                            "5"});
                table16.AddRow(new string[] {
                            "ConstraintDensity",
                            "0.833333"});
                table16.AddRow(new string[] {
                            "ConstraintTightness",
                            "0.5"});
#line 47
        testRunner.Then("the binary CSP problem metrics should be as follows", ((string)(null)), table16, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table17.AddRow(new string[] {
                            "MinimumValue",
                            "2"});
                table17.AddRow(new string[] {
                            "MeanValue",
                            "2.75"});
                table17.AddRow(new string[] {
                            "MaximumValue",
                            "4"});
                table17.AddRow(new string[] {
                            "DistinctValues",
                            "3"});
#line 53
        testRunner.And("the binary CSP variable domain size statistics should be as follows", ((string)(null)), table17, "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table18.AddRow(new string[] {
                            "MinimumValue",
                            "2"});
                table18.AddRow(new string[] {
                            "MeanValue",
                            "2.5"});
                table18.AddRow(new string[] {
                            "MaximumValue",
                            "3"});
                table18.AddRow(new string[] {
                            "DistinctValues",
                            "2"});
#line 59
        testRunner.And("the binary CSP variable degree statistics should be as follows", ((string)(null)), table18, "And ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table19.AddRow(new string[] {
                            "MinimumValue",
                            "0.666667"});
                table19.AddRow(new string[] {
                            "MeanValue",
                            "1.270833"});
                table19.AddRow(new string[] {
                            "MaximumValue",
                            "1.833333"});
                table19.AddRow(new string[] {
                            "DistinctValues",
                            "4"});
#line 65
        testRunner.And("the binary CSP variable sum tightness statistics should be as follows", ((string)(null)), table19, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Solve a binary CSP modelling a solvable puzzle")]
        [Xunit.TraitAttribute("FeatureTitle", "Shikaku")]
        [Xunit.TraitAttribute("Description", "Solve a binary CSP modelling a solvable puzzle")]
        [Xunit.InlineDataAttribute("Backtracking", "None", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "None", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "None", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "None", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "None", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("PartialLookingAhead", "None", new string[0])]
        [Xunit.InlineDataAttribute("PartialLookingAhead", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("PartialLookingAhead", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("PartialLookingAhead", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("FullLookingAhead", "None", new string[0])]
        [Xunit.InlineDataAttribute("FullLookingAhead", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("FullLookingAhead", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("FullLookingAhead", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("MaintainingArcConsistency", "None", new string[0])]
        [Xunit.InlineDataAttribute("MaintainingArcConsistency", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("MaintainingArcConsistency", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("MaintainingArcConsistency", "MaxTightness", new string[0])]
        public void SolveABinaryCSPModellingASolvablePuzzle(string search, string ordering, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Search", search);
            argumentsOfScenario.Add("Ordering", ordering);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Solve a binary CSP modelling a solvable puzzle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 73
        testRunner.Given("I have created a Shikaku puzzle from the following grid", "05 __ __ __ __\r\n__ 05 __ __ __\r\n__ __ 09 __ __\r\n__ __ __ __ 03\r\n03 __ __ __ __", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 81
        testRunner.And("I have modelled the Shikaku puzzle as a binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 82
        testRunner.And(string.Format("I have set the Shikaku binary CSP solver to use the \'{0}\' search strategy", search), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 83
        testRunner.And(string.Format("I have set the Shikaku binary CSP solver to use the \'{0}\' ordering strategy", ordering), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
        testRunner.When("I run the Shikaku binary CSP solver on the binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 85
        testRunner.And("I ask the Shikaku puzzle to validate the proposed solution", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
        testRunner.Then("the validation result should be successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ShikakuFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ShikakuFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
