// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mjt85.Kolyteon.FeatureTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SudokuFeature : object, Xunit.IClassFixture<SudokuFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Sudoku.feature"
#line hidden
        
        public SudokuFeature(SudokuFeature.FixtureData fixtureData, Mjt85_Kolyteon_FeatureTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Sudoku", "As a developer, I want to represent any Sudoku puzzle in code so that I can model" +
                    " and solve it as a binary CSP.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create a serializable puzzle")]
        [Xunit.TraitAttribute("FeatureTitle", "Sudoku")]
        [Xunit.TraitAttribute("Description", "Create a serializable puzzle")]
        public void CreateASerializablePuzzle()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a serializable puzzle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
        testRunner.Given("I have created a Sudoku puzzle from the following grid", "_ 2 _ _ 7 _ 4 3 _\r\n_ 5 1 3 _ _ 2 _ 6\r\n_ 7 _ _ _ 6 _ _ 1\r\n6 _ _ _ _ _ 7 _ 9\r\n7 3 _" +
                        " 5 _ _ _ 1 _\r\n_ _ 9 _ 6 4 _ _ 8\r\n5 6 8 _ 2 7 1 _ 3\r\n3 _ 2 _ 1 _ _ _ _\r\n_ _ 7 _ 8" +
                        " 3 5 2 _", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 17
        testRunner.And("I have serialized the Sudoku puzzle to JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
        testRunner.When("I deserialize a Sudoku puzzle from the JSON", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 19
        testRunner.Then("the deserialized Sudoku puzzle should be the same as the original puzzle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Confirm a proposed solution is valid")]
        [Xunit.TraitAttribute("FeatureTitle", "Sudoku")]
        [Xunit.TraitAttribute("Description", "Confirm a proposed solution is valid")]
        public void ConfirmAProposedSolutionIsValid()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Confirm a proposed solution is valid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
        testRunner.Given("I have created a Sudoku puzzle from the following grid", "_ 9 8 1 5 2 6 3 _\r\n6 _ 3 8 4 7 2 _ 9\r\n2 7 _ 3 6 9 _ 8 5\r\n1 3 4 _ 7 _ 8 9 2\r\n8 2 9" +
                        " 4 _ 1 7 5 6\r\n7 6 5 _ 2 _ 1 4 3\r\n5 8 _ 6 9 4 _ 2 1\r\n9 _ 2 7 1 3 5 _ 8\r\n_ 1 6 2 8" +
                        " 5 9 7 _", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Column",
                            "Row",
                            "Number"});
                table20.AddRow(new string[] {
                            "0",
                            "0",
                            "4"});
                table20.AddRow(new string[] {
                            "0",
                            "8",
                            "3"});
                table20.AddRow(new string[] {
                            "1",
                            "1",
                            "5"});
                table20.AddRow(new string[] {
                            "1",
                            "7",
                            "4"});
                table20.AddRow(new string[] {
                            "2",
                            "2",
                            "1"});
                table20.AddRow(new string[] {
                            "2",
                            "6",
                            "7"});
                table20.AddRow(new string[] {
                            "3",
                            "3",
                            "5"});
                table20.AddRow(new string[] {
                            "3",
                            "5",
                            "9"});
                table20.AddRow(new string[] {
                            "4",
                            "4",
                            "3"});
                table20.AddRow(new string[] {
                            "5",
                            "3",
                            "6"});
                table20.AddRow(new string[] {
                            "5",
                            "5",
                            "8"});
                table20.AddRow(new string[] {
                            "6",
                            "2",
                            "4"});
                table20.AddRow(new string[] {
                            "6",
                            "6",
                            "3"});
                table20.AddRow(new string[] {
                            "7",
                            "1",
                            "1"});
                table20.AddRow(new string[] {
                            "7",
                            "7",
                            "6"});
                table20.AddRow(new string[] {
                            "8",
                            "0",
                            "7"});
                table20.AddRow(new string[] {
                            "8",
                            "8",
                            "4"});
#line 34
        testRunner.And("I have obtained the following list of filled cells as a proposed solution to the " +
                        "Sudoku puzzle", ((string)(null)), table20, "And ");
#line hidden
#line 53
        testRunner.When("I ask the Sudoku puzzle to validate the proposed solution", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 54
        testRunner.Then("the validation result should be successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Model a puzzle as a binary CSP")]
        [Xunit.TraitAttribute("FeatureTitle", "Sudoku")]
        [Xunit.TraitAttribute("Description", "Model a puzzle as a binary CSP")]
        public void ModelAPuzzleAsABinaryCSP()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Model a puzzle as a binary CSP", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
        testRunner.Given("I have created a Sudoku puzzle from the following grid", "4 9 6 5 7 1 8 3 2\r\n2 1 8 9 6 3 7 4 5\r\n7 5 3 8 4 2 1 9 6\r\n5 3 1 7 2 6 9 8 4\r\n6 4 9" +
                        " 3 1 8 2 5 7\r\n8 2 7 4 _ 5 6 1 3\r\n9 _ 2 1 _ 4 3 7 _\r\n1 _ 5 6 _ 7 4 2 _\r\n3 _ 4 2 _" +
                        " 9 5 6 _", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 69
        testRunner.And("I have modelled the Sudoku puzzle as a binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 70
        testRunner.When("I request the binary CSP metrics for the Sudoku puzzle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table21.AddRow(new string[] {
                            "Variables",
                            "10"});
                table21.AddRow(new string[] {
                            "Constraints",
                            "18"});
                table21.AddRow(new string[] {
                            "ConstraintDensity",
                            "0.4"});
                table21.AddRow(new string[] {
                            "ConstraintTightness",
                            "0.375"});
#line 71
        testRunner.Then("the binary CSP problem metrics should be as follows", ((string)(null)), table21, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table22.AddRow(new string[] {
                            "MinimumValue",
                            "1"});
                table22.AddRow(new string[] {
                            "MeanValue",
                            "1.6"});
                table22.AddRow(new string[] {
                            "MaximumValue",
                            "2"});
                table22.AddRow(new string[] {
                            "DistinctValues",
                            "2"});
#line 77
        testRunner.And("the binary CSP variable domain size statistics should be as follows", ((string)(null)), table22, "And ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table23.AddRow(new string[] {
                            "MinimumValue",
                            "0"});
                table23.AddRow(new string[] {
                            "MeanValue",
                            "3.6"});
                table23.AddRow(new string[] {
                            "MaximumValue",
                            "4"});
                table23.AddRow(new string[] {
                            "DistinctValues",
                            "2"});
#line 83
        testRunner.And("the binary CSP variable degree statistics should be as follows", ((string)(null)), table23, "And ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table24.AddRow(new string[] {
                            "MinimumValue",
                            "0.0"});
                table24.AddRow(new string[] {
                            "MeanValue",
                            "1.5"});
                table24.AddRow(new string[] {
                            "MaximumValue",
                            "2.0"});
                table24.AddRow(new string[] {
                            "DistinctValues",
                            "3"});
#line 89
        testRunner.And("the binary CSP variable sum tightness statistics should be as follows", ((string)(null)), table24, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Solve a binary CSP modelling a solvable puzzle")]
        [Xunit.TraitAttribute("FeatureTitle", "Sudoku")]
        [Xunit.TraitAttribute("Description", "Solve a binary CSP modelling a solvable puzzle")]
        [Xunit.InlineDataAttribute("Backtracking", "None", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("Backtracking", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "None", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("Backjumping", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "None", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("GraphBasedBackjumping", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "None", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("ConflictDirectedBackjumping", "MaxTightness", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "None", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "Brelaz", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "MaxCardinality", new string[0])]
        [Xunit.InlineDataAttribute("ForwardChecking", "MaxTightness", new string[0])]
        public void SolveABinaryCSPModellingASolvablePuzzle(string search, string ordering, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Search", search);
            argumentsOfScenario.Add("Ordering", ordering);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Solve a binary CSP modelling a solvable puzzle", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 97
        testRunner.Given("I have created a Sudoku puzzle from the following grid", "_ 2 _ _ 7 _ 4 3 _\r\n_ 5 1 3 _ _ 2 _ 6\r\n_ 7 _ _ _ 6 _ _ 1\r\n6 _ _ _ _ _ 7 _ 9\r\n7 3 _" +
                        " 5 _ _ _ 1 _\r\n_ _ 9 _ 6 4 _ _ 8\r\n5 6 8 _ 2 7 1 _ 3\r\n3 _ 2 _ 1 _ _ _ _\r\n_ _ 7 _ 8" +
                        " 3 5 2 _", ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 109
        testRunner.And("I have modelled the Sudoku puzzle as a binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 110
        testRunner.And(string.Format("I have set the Sudoku binary CSP solver to use the \'{0}\' search strategy", search), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 111
        testRunner.And(string.Format("I have set the Sudoku binary CSP solver to use the \'{0}\' ordering strategy", ordering), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 112
        testRunner.When("I run the Sudoku binary CSP solver on the binary CSP", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 113
        testRunner.And("I ask the Sudoku puzzle to validate the proposed solution", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 114
        testRunner.Then("the validation result should be successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SudokuFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SudokuFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
